        const dataAbnormal = [
        {
        id: '01',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '02',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '03',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '04',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '05',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '06',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '07',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '08',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '09',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '10',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '11',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '12',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '13',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '14',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '15',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '16',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '17',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '18',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '19',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '20',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },
        {
        id: '21',
        name: 'damage to can packaging',
        email: '15 Agustus 2023',
        position: 'Adanya lempengan yang kurang pres',
        company: 'angka riject meningkat',
        country: 'memperbaiki, melepaskan pada bagian yang rusak dan menggantinya',
        },

        ];

        export { dataAbnormal };